{{- if .Values.installClusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-list-services
rules:
- apiGroups: ["*"]
  resources: ["services"]
  verbs: ["list"]

{{- end }}
